services:
  # Traefik API Gateway
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true  # Dashboard 개발용
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=INFO
      - --accesslog=true
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (향후 SSL)
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
    labels:
      - traefik.enable=true
      # CORS 미들웨어 설정
      - traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*
      - traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
      - traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.cors-headers.headers.addvaryheader=true

  resume-service:
    build: 
      context: ./backend
      dockerfile: resume-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - traefik
    volumes:
      - ./backend:/app
    networks:
      - app-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.resume-service.rule=Host(`api.localhost`) && PathPrefix(`/api/v1/resumes`)
      - traefik.http.routers.resume-service.entrypoints=web
      - traefik.http.services.resume-service.loadbalancer.server.port=8001
      - traefik.http.routers.resume-service.middlewares=cors-headers

  interview-service:
    build: 
      context: ./backend
      dockerfile: interview-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - traefik
    volumes:
      - ./backend:/app
    networks:
      - app-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.interview-service.rule=Host(`api.localhost`) && PathPrefix(`/api/v1/interview`)
      - traefik.http.routers.interview-service.entrypoints=web
      - traefik.http.services.interview-service.loadbalancer.server.port=8002
      - traefik.http.routers.interview-service.middlewares=cors-headers
      # 테스트 페이지 라우터 추가
      - traefik.http.routers.interview-test.rule=Host(`api.localhost`) && Path(`/test`)
      - traefik.http.routers.interview-test.entrypoints=web
      - traefik.http.routers.interview-test.service=interview-service
      - traefik.http.routers.interview-test.middlewares=cors-headers

  learning-service:
    build: 
      context: ./backend
      dockerfile: learning-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - traefik
    volumes:
      - ./backend:/app
    networks:
      - app-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.learning-service.rule=Host(`api.localhost`) && PathPrefix(`/api/v1/learning`)
      - traefik.http.routers.learning-service.entrypoints=web
      - traefik.http.services.learning-service.loadbalancer.server.port=8003
      - traefik.http.routers.learning-service.middlewares=cors-headers

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

  # RabbitMQ - 메시지 브로커
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # Redis - 결과 저장소 및 캐시
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Interview Service Celery Worker
  celery-worker-interview:
    build:
      context: ./backend
      dockerfile: interview-service/Dockerfile
    command: celery -A shared.celery_app worker -Q interview_queue --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # Learning Service Celery Worker  
  celery-worker-learning:
    build:
      context: ./backend
      dockerfile: learning-service/Dockerfile
    command: celery -A shared.celery_app worker -Q learning_queue --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # Celery Flower - 모니터링 대시보드
  celery-flower:
    image: mher/flower
    container_name: ai-challenge-flower
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - TZ=Asia/Seoul
    ports:
      - "5555:5555"  # Flower 대시보드
    depends_on:
      - rabbitmq
      - celery-worker-interview
      - celery-worker-learning
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
